### ISSUE TITLE
Stolen Code

### ISSUE THREAD

**Issue by rseigel1** [wix/react-native-wordpress-editor#10]
https://ma.tt/2016/10/wix-and-the-gpl/

Seriously?

You idiots will get what you deserve in the end from WordPress. Good luck...you'll need it.

**Comment by yedidyak** [comment]
You made an account to post this? On an open source project?

**Comment by rseigel1** [comment]
I already had an account Einstein. I just logged in to twist the knife.

**Comment by Vdragon** [comment]
Just passing by...

Open-Source doesn't mean free from copyright issues, especially when it is with a copyleft license
