### ISSUE TITLE
Original GPL License missing

### ISSUE THREAD

**Issue by anttiviljami** [wix/react-native-wordpress-editor#11]
As this is a react native wrapper (a fork) for the original https://github.com/wordpress-mobile/WordPress-Editor-iOS repository, which is Licensed under the GPL, this repo should also retain the GPL license.

I can't point to the exact commit where the license was either intentionally, or mistakenly left out, but please re-add the license as seen here:

https://github.com/wordpress-mobile/WordPress-Editor-iOS/blob/develop/LICENSE

Related post from Matt Mullenweg: 

https://ma.tt/2016/10/wix-and-the-gpl/

**Comment by n1rvana** [comment]
Time to cut Wordpress and their shady relicensing of MIT code as GPL out of the loop and go straight to the actual MIT open source code.

**Comment by bet0x** [comment]
They have to release the FULL APP now.

**Comment by ghost** [comment]
Hi all,
Thanks for the feedback and especially the PR!
We are currently on it with our legal department.

**Comment by leokoo** [comment]
actually if any part of your app uses GPL, you need to release the entire app as GPL. So, to keep the changes to yourself, go back to the original MIT version (without commits from Automattic/WordPress)

**Comment by talkol** [comment]
Regarding the GPL, following commit closes this issue:
https://github.com/wix/react-native-wordpress-editor/commit/b0ac0e23116228341d8a8e2d957a888fcfce6fcc

Please reopen if you have anything to add
